### Combine the data to make the final dataset for fine-tuning

In [11]:
import pandas as pd

### For now we have three datasets:

Two of them have binary labels (either true or false) and one has more specific labels (half-true, mostly-true, false, etc.). For now it is suggested to focus on the binary classification, since the more detailed dataset has far less observations, and it might introduce the additional complexity. The model can always be further fine-tuned on it later

In [17]:
fake_news_all = pd.read_csv('fake_news_all.csv')
fake_news_all

,title,text,label
0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1
1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1
2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0
3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1
4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0
...,...,...,...
40582,Sanders at Vatican says rich-poor gap worse th...,VATICAN CITY (Reuters) - U.S. presidential can...,1
40583,how trump happened,force and fanaticism wahhabism in saudi arabi...,1
40584,Turkey will take two steps if Germany takes on...,"ISTANBUL (Reuters) - Turkey, whose relations w...",1
40585,BREAKING: DEVICE THAT BUSTED HILLARY CLINTON D...,Here s why Clinton and Abedin should be flippi...,0
40586,occupier david fry released from jail im reall...,one twitter user once asked me is it too much ...,0

In [18]:
welfake_data = pd.read_csv('welfake_data.csv')
welfake_data

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [19]:
all_data = pd.concat([fake_news_all, welfake_data])
all_data.index = range(len(all_data))
all_data

,title,text,label
0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1
1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1
2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0
3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1
4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0
...,...,...,...
112716,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
112717,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
112718,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
112719,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
112720,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [20]:
# ensure there are no duplicates
all_data = all_data.drop_duplicates(subset=['text'], keep='first')
all_data.index = range(len(all_data))
all_data

,title,text,label
0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1
1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1
2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0
3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1
4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0
...,...,...,...
84172,An Unlikely Contender Rises in France as the A...,"PARIS — In the age of Donald J. Trump, “Bre...",0
84173,Determined to kill: Can tough gun laws end mas...,The flag at Desert Hot Springs' Condor Gun Sho...,0
84174,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
84175,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
84176,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0

**So actually there were duplicates. Anyway, we still have a lot of training samples for fine-tuning the data.**

### Convert the data to the correct format for the fine-tuning

+ Merge the title and the text column for simplicity

+ Change the column name so that it is consistent with the format of the other dataset, and they satisfy the standards

In [21]:
all_data['statement'] = all_data['title'] + ': ' + all_data['text']
all_data = all_data[['statement', 'label']]  # Keep only the necessary columns
all_data.rename(columns={'label': 'labels'}, inplace=True)
all_data

/var/folders/d3/77342y0n20qgyxgcd7fxq_ww0000gn/T/ipykernel_92503/1517852864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data['statement'] = all_data['title'] + ': ' + all_data['text']
/var/folders/d3/77342y0n20qgyxgcd7fxq_ww0000gn/T/ipykernel_92503/1517852864.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data.rename(columns={'label': 'labels'}, inplace=True)

                                               statement  labels
0      Palestinians switch off Christmas lights in Be...       1
1      China says Trump call with Taiwan president wo...       1
2       FAIL! The Trump Organization’s Credit Score W...       0
3      Zimbabwe military chief's China trip was norma...       1
4      THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...       0
...                                                  ...     ...
84172  An Unlikely Contender Rises in France as the A...       0
84173  Determined to kill: Can tough gun laws end mas...       0
84174  Russians steal research on Trump in hack of U....       0
84175  Migrants Refuse To Leave Train At Refugee Camp...       0
84176  Trump tussle gives unpopular Mexican leader mu...       0

[84177 rows x 2 columns]

In [22]:
all_data['statement'][0]

'Palestinians switch off Christmas lights in Bethlehem in anti-Trump protest: RAMALLAH, West Bank (Reuters) - Palestinians switched off Christmas lights at Jesus  traditional birthplace in Bethlehem on Wednesday night in protest at U.S. President Donald Trump s decision to recognize Jerusalem as Israel s capital. A Christmas tree adorned with lights outside Bethlehem s Church of the Nativity, where Christians believe Jesus was born, and another in Ramallah, next to the burial site of former Palestinian leader Yasser Arafat, were plunged into darkness.  The Christmas tree was switched off on the order of the mayor today in protest at Trump s decision,  said Fady Ghattas, Bethlehem s municipal media officer.  He said it was unclear whether the illuminations would be turned on again before the main Christmas festivities. In a speech in Washington, Trump said he had decided to recognize Jerusalem as Israel s capital and move the U.S. embassy to the city. Israeli Prime Minister Benjamin Netanyahu said Trump s move  marked the beginning of a new approach to the Israeli-Palestinian conflict and said it was an  historic landmark . Arabs and Muslims across the Middle East condemned the U.S. decision, calling it an incendiary move in a volatile region and the European Union and United Nations also voiced alarm at the possible repercussions for any chances of reviving Israeli-Palestinian peacemaking. '

In [23]:
all_data['statement'][84175]

'Migrants Refuse To Leave Train At Refugee Camp In Hungary: Migrants Refuse To Leave Train At Refugee Camp In Hungary\n\nThousands of migrants flooded into a train station in the Hungarian capital Thursday after police lifted a two-day blockade, but some who boarded a train they thought was going to Germany ended up instead at a refugee camp just miles from Budapest.\n\nThe Associated Press reports that "excited migrants piled into a newly arrived train at the Keleti station in Hungary\'s capital despite announcements in Hungarian and English that all services from the station to Western Europe had been canceled. A statement on the main departures board said no more trains to Austria or Germany would depart \'due to safety reasons until further notice!\'\n\n"Many migrants, who couldn\'t understand either language and were receiving no advice from Hungarian officials, scrambled aboard in a standing-room-only crush and hoped for the best," the AP said.\n\nScuffles broke out when police ordered the passengers off the train at Bicske, according to the BBC.\n\nMeanwhile, Hungary\'s prime minister says his country is doing all it can to manage a growing migrant crisis, even as European officials said they will meet this month in Brussels to discuss an effort to "strengthen the European response" to the situation.\n\nViktor Orban said the influx of refugees into his country is really "a German problem" because that is the intended destination for most of them. Hungarians, along with other Europeans, are "full of fear" he says, because "they see that the European leaders, among them the prime ministers, are not able to control the situation."\n\n"If we would create an image ... just come because we are ready to accept everybody, that would be a moral failure, because that is not the case," Orban said after a meeting with European Parliament President Martin Schulz, according to The Washington Post. "The moral human thing is to make clear, please don\'t come. Why do you have to go from Turkey to Europe? Turkey is a safe country. Stay there. It\'s risky to come."\n\nMeanwhile, Voice of America reports that British, French and German officials have called for urgent action and plan to hold talks on Sept. 14 in Brussels to address the crisis.\n\nVOA reports: "The three ministers also called for better processing of migrants in Italy and Greece."\n\nAs we\'ve reported, the United Nations believes that more than 300,000 migrants have set out for Europe from North Africa and the Middle East on the Mediterranean Sea so far this year, a 40 percent increase on all of last year.\n\nAs NPR\'s Middle East editor Larry Kaplow writes: "On any given day now, hundreds of people, perhaps thousands, are drifting in ships or clinging to boats that are little more than inflatable rafts. They go in other ways, too. Jumping fences in Morocco to get to Spanish territory. Cramming into trucks from Turkey. Riding trains across Europe."'

In [24]:
all_data.to_csv('all_news_data.csv', index=False)

In [25]:
all_data.to_parquet('all_news_data.parquet', index=False)